# Generated by Django 5.0.7 on 2024-07-19 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_simulation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policy",
            old_name="policy",
            new_name="text",
        ),
    ]
