# Generated by Django 5.0.7 on 2024-07-19 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_rename_simulation_reaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "Policies"},
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="reaction",
            new_name="text",
        ),
    ]
