# Generated by Django 5.0.7 on 2024-07-19 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_policy_options_rename_reaction_reaction_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="policy",
        ),
        migrations.DeleteModel(
            name="Policy",
        ),
    ]
