# Generated by Django 5.0.7 on 2024-07-19 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_reaction_policy_delete_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("policy", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="reaction",
            name="simulation",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.simulation",
            ),
            preserve_default=False,
        ),
    ]
