# Generated by Django 5.0.7 on 2024-07-19 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_reaction_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
