# Generated by Django 5.0.7 on 2024-07-19 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_reaction_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="completed_at",
        ),
    ]
