# Generated by Django 5.0.7 on 2024-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_reaction_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="prompt",
        ),
        migrations.AddField(
            model_name="reaction",
            name="system_prompt",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reaction",
            name="user_prompt",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
