# Generated by Django 5.0.7 on 2024-07-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_rename_prompt_persona_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="sentiment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
